{"name": "test_open_login_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator\n  (Session info: chrome=123.0.6312.86)\nStacktrace:\n\tGetHandleVerifier [0x00CF4CC3+225091]\n\t(No symbol) [0x00C24E11]\n\t(No symbol) [0x00AC9A7A]\n\t(No symbol) [0x00B01689]\n\t(No symbol) [0x00B0188B]\n\t(No symbol) [0x00B37882]\n\t(No symbol) [0x00B1F5A4]\n\t(No symbol) [0x00B35CB0]\n\t(No symbol) [0x00B1F2F6]\n\t(No symbol) [0x00AF79B9]\n\t(No symbol) [0x00AF879D]\n\tsqlite3_dbdata_init [0x01169A63+4064547]\n\tsqlite3_dbdata_init [0x0117106A+4094762]\n\tsqlite3_dbdata_init [0x0116B968+4072488]\n\tsqlite3_dbdata_init [0x00E6C9C9+930953]\n\t(No symbol) [0x00C307E4]\n\t(No symbol) [0x00C2AD08]\n\t(No symbol) [0x00C2AE31]\n\t(No symbol) [0x00C1CAA0]\n\tBaseThreadInitThunk [0x75EA7BA9+25]\n\tRtlInitializeExceptionChain [0x76F9BE3B+107]\n\tRtlClearBits [0x76F9BDBF+191]", "trace": "self = <PyPi_home_page_test.TestPyPiHomePage object at 0x000001E07FDD6CF0>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"655349af21b314f968c854f448d198ba\")>\nlogger = <Logger selenium (DEBUG)>\n\n    @pytest.mark.sanity\n    def test_open_login_page(self, driver, logger):\n        page_login = PageLogin(driver, logger)\n        page_login.open()\n        page_login.type_email_or_phone()\n        page_login.type_password()\n        page_login.click_on_sign_in_button()\n    \n        #this object for linkedin homepage\n        page_home_page = PageHomePage(driver, logger)\n>       page_home_page.type_nrobo_search_field()\n\ntests\\web\\PyPi_home_page_test.py:74: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\PageHomePage.py:26: in type_nrobo_search_field\n    self.send_keys(*self.keys.ENTER)\n.venv\\Lib\\site-packages\\nrobo\\selenese\\__init__.py:999: in send_keys\n    self.find_element(by, value).send_keys(text)\n.venv\\Lib\\site-packages\\nrobo\\selenese\\__init__.py:541: in find_element\n    .until(expected_conditions.presence_of_element_located((by, value)))\n.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:96: in until\n    value = method(self._driver)\n.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:84: in _predicate\n    return driver.find_element(*locator)\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:741: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x000001E07FCF9130>\nresponse = {'status': 400, 'value': '{\"value\":{\"error\":\"invalid argument\",\"message\":\"invalid argument: invalid locator\\\\n  (Sessi...dInitThunk [0x75EA7BA9+25]\\\\n\\\\tRtlInitializeExceptionChain [0x76F9BE3B+107]\\\\n\\\\tRtlClearBits [0x76F9BDBF+191]\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator\nE         (Session info: chrome=123.0.6312.86)\nE       Stacktrace:\nE       \tGetHandleVerifier [0x00CF4CC3+225091]\nE       \t(No symbol) [0x00C24E11]\nE       \t(No symbol) [0x00AC9A7A]\nE       \t(No symbol) [0x00B01689]\nE       \t(No symbol) [0x00B0188B]\nE       \t(No symbol) [0x00B37882]\nE       \t(No symbol) [0x00B1F5A4]\nE       \t(No symbol) [0x00B35CB0]\nE       \t(No symbol) [0x00B1F2F6]\nE       \t(No symbol) [0x00AF79B9]\nE       \t(No symbol) [0x00AF879D]\nE       \tsqlite3_dbdata_init [0x01169A63+4064547]\nE       \tsqlite3_dbdata_init [0x0117106A+4094762]\nE       \tsqlite3_dbdata_init [0x0116B968+4072488]\nE       \tsqlite3_dbdata_init [0x00E6C9C9+930953]\nE       \t(No symbol) [0x00C307E4]\nE       \t(No symbol) [0x00C2AD08]\nE       \t(No symbol) [0x00C2AE31]\nE       \t(No symbol) [0x00C1CAA0]\nE       \tBaseThreadInitThunk [0x75EA7BA9+25]\nE       \tRtlInitializeExceptionChain [0x76F9BE3B+107]\nE       \tRtlClearBits [0x76F9BDBF+191]\n\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:229: InvalidArgumentException"}, "attachments": [{"name": "screenshot", "source": "2cf0440a-ff52-4be3-aa5e-7c11da42e98b-attachment.png", "type": "image/png"}, {"name": "log", "source": "9efb07d9-3197-4b07-9608-6965728f3edd-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "30d07d0d-d7d7-4816-ba72-29170fabe050-attachment.txt", "type": "text/plain"}], "start": 1711966002148, "stop": 1711966021707, "uuid": "e2a81e34-611a-43cd-bda6-c4e820fbbf7f", "historyId": "071451c7a91a1c5962dabdf4eaf38ac4", "testCaseId": "071451c7a91a1c5962dabdf4eaf38ac4", "fullName": "tests.web.PyPi_home_page_test.TestPyPiHomePage#test_open_login_page", "labels": [{"name": "tag", "value": "sanity"}, {"name": "parentSuite", "value": "tests.web"}, {"name": "suite", "value": "PyPi_home_page_test"}, {"name": "subSuite", "value": "TestPyPiHomePage"}, {"name": "host", "value": "Vishalvivek"}, {"name": "thread", "value": "18208-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.web.PyPi_home_page_test"}]}